"use strict";

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

function isEmptyDir(grunt, dirPath) {
  if( grunt.file.isDir(dirPath) ){
    let files = grunt.file.expand( { 'cwd' : dirPath }, '*');
    return files.length === 0;
  }
  return false;
}

/**
 * Create a yaml file containing an Ansible playbook generated by scanning
 * the content of a folder (source folder)
 */
exports.createPlaybook = function(grunt, role) {

  // validate arguments ////////////////////////////////////////////////////////
  if( ! role ) {
    grunt.log.error('missing role argument (ex: "editorial", "archive")');
    return false;
  }

  grunt.config.requires('pkg');
  let pkg = grunt.config('pkg');

  grunt.config.requires('playbook.baseFolder');
  let baseFolder = grunt.config('playbook.baseFolder');
  if(  ! grunt.file.isDir(baseFolder) ) {
    grunt.log.error('Base Folder not found : '+baseFolder);
    return false;
  }
  // the Source folder (where source files are located) is built as a relative path
  // using the baseFolder + role
  let srcFolder = path.posix.join(baseFolder,role);
  if(  ! grunt.file.isDir(srcFolder) ) {
    grunt.log.error('Source Folder not found : '+srcFolder);
    return false;
  }
  // The is the remote folder base path. All remote path are assumed to be inside this
  // folder
  grunt.config.requires('playbook.remoteBasePath');
  let remoteBasePath = grunt.config('playbook.remoteBasePath');

  grunt.verbose.ok('base Folder      : ' + baseFolder);
  grunt.verbose.ok('role             : ' + role );
  grunt.log.ok('src file Folder  : ' + srcFolder);
  grunt.log.ok('package version  : ' + grunt.config('pkg.version'));

  ////////////////////////////////////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////////////////

  let ansiblePlaybook = {
    'hosts' : role
  };
  let srcRolePath = path.posix.join('..', role);
  let task = {
    'createEmptyDir' : [],
    'copyRoleDir'    : [{
      'name' : `copy content of folder ${srcRolePath} to ${remoteBasePath}`,
      'copy' : {
        'src' : `${srcRolePath}/`,
        'dest' : remoteBasePath,
        'backup' : 'yes'
      }
    }],
    'changeFileMode' : []
  };
  let remoteName = '';
  let sourceName = '';

  let srcFile = grunt.file.expand({
    'cwd' : srcFolder
  },['**/**'])
  .filter( x => x.trim().length > 0)
  .forEach(file => {
        //console.log(file);  // relative to baseFolder
        let filePath = path.posix.join(srcFolder,file);
        grunt.verbose.writeln(filePath);

        if( isEmptyDir(grunt, filePath)) {
          remoteName = path.posix.join(remoteBasePath, file);
          task.createEmptyDir.push({
            "name" : `create empty folder ${remoteName}`,
            "file" : {
              'path'  : remoteName,
              'state' : 'directory'
            }
          });
        } else
        if( grunt.file.isFile(filePath) &&
          ['.bash', '.sh'].indexOf(path.extname(file)) !== -1 ) {
            remoteName = path.posix.join(remoteBasePath, file);
            sourceName =  path.posix.join('..', role, file);
            task.changeFileMode.push(
              {
                'name' : `chmod on file ${remoteName}`,
                'file' : {
                  'path' : remoteName,
                  'mode' : 'u=rwx,g=rx,o=rx'
                }
              }
            );
        } // else we are dealing with a non-empty folder that will
        // be created automatically when the root folder will be copied
    }
  );
  ansiblePlaybook.tasks = task.createEmptyDir
    .concat(task.copyRoleDir)
    .concat(task.changeFileMode);

  grunt.log.ok(`stats :
    emptyDirCreate = ${task.createEmptyDir.length},
    changeFileMode = ${task.changeFileMode.length}
    totalTasks     = ${ansiblePlaybook.tasks.length}
  `);

  // dump playbook
  // ////////////////////////////////////////////////////////////////////////
  // create folder if needed

  let playbookFolder = path.posix.join(baseFolder, 'playbook');
  if( ! grunt.file.exists(playbookFolder)) {
    grunt.verbose.writeln('creating ansible playbook folder : '+playbookFolder);
    grunt.file.mkdir(playbookFolder);
  }

  // prepare playbook file
  let playbookFilename = `${role}.yaml`;
  let playbookPath = path.posix.join(playbookFolder, playbookFilename);
  if( grunt.file.exists(playbookPath)) {
    grunt.file.delete(playbookPath);
  }

  // for debug only : save the JSON version of the playbook
  fs.writeFileSync(
    playbookPath+'.json',
    JSON.stringify(ansiblePlaybook, null, 2)
  );

  // serialize ansiblePlaybook to YAML file (playbookPath)

  let yamlString = yaml.safeDump ([ansiblePlaybook], {
    'json' : true
  });
  fs.writeFileSync(playbookPath, yamlString);
  grunt.log.ok('playbook created in ' + playbookPath);
};
